//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafeSure.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Policies = new HashSet<Policy>();
            this.Endorsements = new HashSet<Endorsement>();
        }
    
        public int customer_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public string Customer_name { get; set; }
        public string Customer_address { get; set; }
        public string Mobile_number { get; set; }
        public string gender { get; set; }
        public string Smoker { get; set; }
        public Nullable<System.DateTime> Date_of_Birth { get; set; }
        public string Hobbies { get; set; }
        public string endorsementStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Policy> Policies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Endorsement> Endorsements { get; set; }
        public virtual InsuranceProduct InsuranceProduct { get; set; }
    }
}
